language: groovy
sudo: false
jdk:
  - oraclejdk8

branches:
  only:
    - add_support_for-travis-ci.org

before_install:
  - rm -rf ~/.sdkman
  - curl -s https://get.sdkman.io | bash
  - echo 'sdkman_auto_answer=true' > ~/.sdkman/etc/config
  - source ~/.sdkman/bin/sdkman-init.sh
  - GRAILS_VERSION=`grep '^\s*app.grails.version' application.properties | sed -e 's/^\s*app\.grails\.version=//g' | tr -d "\r"`
  - echo "GRAILS_VERSION:$GRAILS_VERSION"
  - sdk install grails $GRAILS_VERSION || true

script:
  - grails clean && grails refresh-dependencies --non-interactive && grails dependency-report --non-interactive && grails prod maven-install --non-interactive --stacktrace
