version: 2

jobs:
  build:
    working_directory: ~/circleci-nsl-domain-plugin

    environment:
      TZ: "/usr/share/zoneinfo/Australia/Canberra"

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    branches:
      only:
        - add_support_for-circleci.com

    steps:
      - checkout
      - run: |
          rm -rf ~/.sdkman
          curl -s http://get.sdkman.io | bash
          echo "sdkman_auto_answer=true" > ~/.sdkman/etc/config
          source ~/.sdkman/bin/sdkman-init.sh
          GRAILS_VERSION=`grep '^\s*app.grails.version' application.properties | sed -e 's/^\s*app\.grails\.version=//g' | tr -d "\r"`
          echo "GRAILS_VERSION:$GRAILS_VERSION"
          sdk install grails $GRAILS_VERSION || true
          grails clean && grails refresh-dependencies --non-interactive && grails dependency-report --non-interactive && grails prod maven-install --non-interactive --stacktrace
