ALTER TABLE reference ALTER COLUMN citation TYPE VARCHAR(4000);
ALTER TABLE reference ALTER COLUMN citation_html TYPE VARCHAR(4000);
ALTER TABLE reference ALTER COLUMN edition TYPE VARCHAR(100);
ALTER TABLE reference ALTER COLUMN pages TYPE VARCHAR(1000);
ALTER TABLE reference ALTER COLUMN published_location TYPE VARCHAR(1000);
ALTER TABLE reference ALTER COLUMN publisher TYPE VARCHAR(1000);
ALTER TABLE reference ALTER COLUMN volume TYPE VARCHAR(100);

UPDATE db_version
SET version = 12
WHERE id = 1;
